services:
  db:
    image: postgres:16
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./logic
    env_file:
      - ./logic/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logic:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./sos
    ports:
      - "3000:3000"

    environment:
      - PYTHONPATH=/app
    env_file:
      - ./sos/.env
    depends_on:
      - backend
    volumes:
      - ./sos:/app
volumes:
  postgres_data:
