version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crisis_aid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./logic
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/crisis_aid
      SECRET_KEY: your-secret-key-here
      CORS_ORIGINS: "http://localhost:3000"
    volumes:
      - ./logic:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        python scripts/migrate.py &&
        python seed.py &&
        uvicorn api:app --host 0.0.0.0 --port 8000 --reload
      "

  frontend:
    build: ./sos
    volumes:
      - ./sos:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
      NODE_ENV: development
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
