services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crisis_aid
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./logic
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/crisis_aid
      SECRET_KEY: your-secret-key-here
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        python scripts/migrate.py &&
        python seed.py &&
        uvicorn api:app --host 0.0.0.0 --port 8000 --reload
      "
    volumes:
      - ./logic:/app
      - backend_venv:/app/venv
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./sos
      args:
        - NEXT_PUBLIC_API_URL=http://backend:8000
        - NODE_ENV=development
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=development
    command: >
      sh -c "
        npm run build &&
        npm run dev
      "
    depends_on:
      - backend
    volumes:
      - ./sos:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:
  backend_venv:
